function [] = generateMGSettings(visible)
    
    if ~(strcmp(visible,'on') || strcmp(visible,'off')) 
        disp('WRONG INPUT! SettingUIControls not generated! Check: generateMGSettings-function');
        return;
    end

    % get global variables
    global panelSettings_h;
    
    % set global variables
    global MGtext1_h;       % text: N
    global MGtext2_h;       % text: ALIVE
    global MGtext3_h;       % text: PROB_MUTATION
    global MGtext4_h;       % text: VISIBILITY
    global MGtext5_h;       % text: MAJ_REQUIRED
    global MGtext6_h;       % text: PROB_UPDATE
    global MGeditbox1_h;        % value: N
    global MGeditbox2_h;        % value: ALIVE
    global MGeditbox3_h;        % value: PROB_MUTATION
    global MGeditbox4_h;        % value: VISIBILITY
    global MGeditbox5_h;        % value: MAJ_REQUIRED
    global MGeditbox6_h;        % value: PROB_UPDATE
    
    
    
    %% STATIC TEXT
    % static: N
    MGtext1_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'N. . . . . . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.75 0.9 0.16]);

    % static: ALIVE
    MGtext2_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'ALIVE . . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.65 0.9 0.16]);

    % static: PROB_MUTATION
    MGtext3_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'PROB_MUTATION. . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.55 0.9 0.16]);

    % static: VISIBILITY
    MGtext4_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'VISIBILITY. . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.45 0.9 0.16]);

    % static: MAJ_REQUIRED
    MGtext5_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'MAJ_REQUIRED . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.35 0.9 0.16]);
    
    % static: PROB_UPDATE
    MGtext6_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'PROB_UPDATE . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.25 0.9 0.16]);

    
    
    %% INSERT VALUES (editboxes/checkbox)
    % insert: N
    MGeditbox1_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.85 0.25 0.08]);

    % insert: ALIVE
    MGeditbox2_h = uicontrol('Style', 'edit', ...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.75 0.25 0.08]);

    % insert: PROB_MUTATION
    MGeditbox3_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.65 0.25 0.08]);       

    % insert: VISIBILITY
    MGeditbox4_h = uicontrol('Style', 'edit', ...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.55 0.25 0.08]);

    % insert: MAJ_REQUIRED
    MGeditbox5_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.7 0.45 0.25 0.08]);
        
    % insert: PROB_UPDATE
    MGeditbox6_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.7 0.35 0.25 0.08]);

    

    %% ADD TAGS AND CALLBACKS
    MGeditbox1_h.Tag = 'MG.N';               
    MGeditbox2_h.Tag = 'MG.ALIVE';           
    MGeditbox3_h.Tag = 'MG.PROB_MUTATION';   
    MGeditbox4_h.Tag = 'MG.VISIBILITY';  
    MGeditbox5_h.Tag = 'MG.MAJ_REQUIRED';       
    MGeditbox6_h.Tag = 'MG.PROB_UPDATE';
    
    MGeditbox1_h.Callback  = @edit_fun;
    MGeditbox2_h.Callback  = @edit_fun;
    MGeditbox3_h.Callback  = @edit_fun;
    MGeditbox4_h.Callback  = @edit_fun;
    MGeditbox5_h.Callback  = @edit_fun;
    MGeditbox6_h.Callback  = @edit_fun;
    
    
    
end



