function [] = generateINFSettings(visible)
    
    if ~(strcmp(visible,'on') || strcmp(visible,'off')) 
        disp('WRONG INPUT! SettingUIControls not generated! Check: generateINFSettings-function');
        return;
    end
    
    % get global variables
    global panelSettings_h;
    
    % set global variables
    global INFtext1_h;          % text: N
    global INFtext2_h;          % text: INF_CELLS
    global INFeditbox1_h;           % value: N
    global INFeditbox2_h;           % value: INF_CELLS
    
    
    
    %% STATIC TEXT
    % static: N
    INFtext1_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'N. . . . . . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.75 0.9 0.16]);

    % static: INF_CELLS
    INFtext2_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'INF_CELLS . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.65 0.9 0.16]);
    
    
    
    %% INSERT VALUES (editboxes/checkbox)
    % insert: N
    INFeditbox1_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...    
        'Units', 'normalized', ...
        'Position', [0.70 0.85 0.25 0.08]);

    % insert: INF_CELLS
    INFeditbox2_h = uicontrol('Style', 'edit', ...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...       
        'Units', 'normalized', ...
        'Position', [0.70 0.75 0.25 0.08]);

    

    %% ADD TAGS AND CALLBACKS
    INFeditbox1_h.Tag  = 'INF.N';               
    INFeditbox2_h.Tag  = 'INF.INF_CELLS';           
    INFeditbox1_h.Callback  = @edit_fun;
    INFeditbox2_h.Callback  = @edit_fun;
    
    
    
end