function [] = generateGOLSettings(visible)
    
    if ~(strcmp(visible,'on') || strcmp(visible,'off')) 
        disp('WRONG INPUT! SettingUIControls not generated! Check: generateGOLSettings-function');
        return;
    end
    
    % get global variables
    global panelSettings_h;
    
    % set global variables
    global GOLtext1_h;          % text: N
    global GOLtext2_h;          % text: ALIVE
    global GOLtext3_h;          % text: PROB_MUTATION
    global GOLtext4_h;          % text: RANDOM_GLODERS
    global GOLtext5_h;          % text: PAUSE
    global GOLeditbox1_h;       % value: N
    global GOLeditbox2_h;       % value: ALIVE
    global GOLeditbox3_h;       % value: PROB_MUTATION
    global GOLcheckbox4_h;      % value: RANDOM_GLIDERS (checkbox)
    global GOLeditbox5_h;       % value: PAUSE

    
    %% STATIC TEXT
    % static: N
    GOLtext1_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'N. . . . . . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.75 0.9 0.16]);

    % static: ALIVE
    GOLtext2_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'ALIVE. . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.65 0.9 0.16]);

    % static: PROB_MUTATION
    GOLtext3_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'PROB_MUTATION. . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.55 0.9 0.16]);

    % static: RANDOM_GLIDERS
    GOLtext4_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'RANDOM_GLIDERS. . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.45 0.9 0.16]);

    % static: PAUSE
    GOLtext5_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'PAUSE . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.35 0.9 0.16]);


    %% INSERT VALUES (editboxes/checkbox)
    % insert: N
    GOLeditbox1_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.85 0.25 0.08]);

    % insert: ALIVE
    GOLeditbox2_h = uicontrol('Style', 'edit', ...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.75 0.25 0.08]);

    % insert: PROB_MUTATION
    GOLeditbox3_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.65 0.25 0.08]);       

    % insert: RANDOM GLIDERS
    GOLcheckbox4_h = uicontrol('Style', 'checkbox', ...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.79 0.55 0.25 0.08]);

    % insert: PAUSE
    GOLeditbox5_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.45 0.25 0.08]);    



    %% ADD TAGS AND CALLBACKS
    GOLeditbox1_h.Tag  = 'GOL.N';               
    GOLeditbox2_h.Tag  = 'GOL.ALIVE';           
    GOLeditbox3_h.Tag  = 'GOL.PROB_MUTATION';   
    GOLcheckbox4_h.Tag = 'GOL.RANDOM_GLIDERS';  
    GOLeditbox5_h.Tag  = 'GOL.PAUSE';       
    
    GOLeditbox1_h.Callback  = @edit_fun;
    GOLeditbox2_h.Callback  = @edit_fun;
    GOLeditbox3_h.Callback  = @edit_fun;
    GOLcheckbox4_h.Callback = @edit_fun;
    GOLeditbox5_h.Callback  = @edit_fun;
    
    
    
end