function [] = generateWOLFSettings(visible)

    if ~(strcmp(visible,'on') || strcmp(visible,'off')) 
        disp('WRONG INPUT! SettingUIControls not generated! Check: generateWOLFSettings-function');
        return;
    end

    % get global variables
    global panelSettings_h;
    
    % set global variables
    global WOLFtext1_h;         % text: RULE
    global WOLFtext2_h;         % text: INFINITYLOOP
    global WOLFtext3_h;         % text: RENDER SPEED
    global WOLFeditbox1_h;          % value: RULE
    global WOLFslider2_h;           % value: RULE
    global WOLFcheckbox3_h;         % value: INFINITYLOOP
    global WOLFeditbox4_h;          % value: RENDER SPEED

    
    
    %% STATIC TEXT
    % static: RULE
    WOLFtext1_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'RULE. . . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.75 0.9 0.16]);

    % static: INFINITYLOOP
    WOLFtext2_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'INFINITYLOOP . . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.58 0.9 0.16]);
    
    % static: INFINITYLOOP
    WOLFtext3_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'RENDER SPEED . . . . . . . . ', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.48 0.9 0.16]);
    
    
    %% INSERT VALUES (editboxes/checkbox)
    % insert: RULE
    WOLFeditbox1_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...    
        'Units', 'normalized', ...
        'Position', [0.70 0.85 0.25 0.08]);

    % insert: RULE_SLIDER
    WOLFslider2_h = uicontrol('Style', 'slider',...
        'Parent', panelSettings_h, ...
        'Min', 0, 'Max', 255, ...
        'SliderStep', [1/255 1/255], ...
        'Visible', visible, ...    
        'Units', 'normalized', ...
        'Position', [0.05 0.78 0.9 0.05]);
    
    % insert: INFINITYLOOP
    WOLFcheckbox3_h = uicontrol('Style', 'checkbox', ...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...       
        'Units', 'normalized', ...
        'Position', [0.79 0.68 0.25 0.08]);

    % insert: RENDER SPEED
    WOLFeditbox4_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...    
        'Units', 'normalized', ...
        'Position', [0.70 0.58 0.25 0.08]);

   
    

    %% ADD TAGS AND CALLBACKS
    WOLFeditbox1_h.Tag  = 'WOLF.RULE';               
    WOLFslider2_h.Tag   = 'WOLF.RULE_SLIDER';
    WOLFcheckbox3_h.Tag = 'WOLF.INFINITYLOOP';   
    WOLFeditbox4_h.Tag = 'WOLF.RENDERSPEED';            
    
    WOLFeditbox1_h.Callback  = @edit_fun;
    WOLFslider2_h.Callback   = @edit_fun;
    WOLFcheckbox3_h.Callback = @edit_fun;
    WOLFeditbox4_h.Callback = @edit_fun;
    
    
    
end