function [] = generateCCSettings(visible)
    
    if ~(strcmp(visible,'on') || strcmp(visible,'off')) 
        disp('WRONG INPUT! SettingUIControls not generated! Check: generateCCSettings-function');
        return;
    end
    
    % get global variables
    global panelSettings_h;
    
    % set global variables
    global CCtext1_h;          % text: N
    global CCtext2_h;          % text: GROUPS
    global CCtext3_h;          % text: PROB_COPY
    global CCtext4_h;          % text: PROB_CONTRARIAN
    global CCtext5_h;          % text: TYPE
    
    global CCeditbox1_h;       % value: N
    global CCeditbox2_h;       % value: GROUPS
    global CCeditbox3_h;       % value: PROB_COPY
    global CCeditbox4_h;       % value: PROB_CONTRARIAN
    global CCpopupmenu5_h;     % value: TYPE (popupmenu)

    
    
    %% STATIC TEXT
    % static: N
    CCtext1_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'N. . . . . . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.75 0.9 0.16]);

    % static: GROUPS
    CCtext2_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'GROUPS. . . . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.65 0.9 0.16]);

    % static: PROB_COPY
    CCtext3_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'PROB_COPY . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.55 0.9 0.16]);

    % static: PROB_CONTRARIAN
    CCtext4_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'PROB_CONTRARIAN . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.45 0.9 0.16]);

    % static: TYPE
    CCtext5_h = uicontrol('Style', 'text',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'HorizontalAlignment', 'left', ...
        'String', 'TYPE . . . . . . . . . . . . .', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.35 0.9 0.16]);

   

    %% INSERT VALUES (editboxes/checkbox)
    % insert: N
    CCeditbox1_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.85 0.25 0.08]);

    % insert: GROUPS
    CCeditbox2_h = uicontrol('Style', 'edit', ...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.75 0.25 0.08]);

    % insert: PROB_COPY
    CCeditbox3_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.65 0.25 0.08]);       

    % insert: PROB_CONTRARIAN
    CCeditbox4_h = uicontrol('Style', 'edit',...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'Units', 'normalized', ...
        'Position', [0.70 0.55 0.25 0.08]);       

    % insert: TYPE
    CCpopupmenu5_h = uicontrol('Style', 'popup', ...
        'Parent', panelSettings_h, ...
        'Visible', visible, ...
        'String', {'equally','domination'}, ...
        'Units', 'normalized', ...
        'Position', [0.57 0.45 0.38 0.08]);


    
    %% ADD TAGS AND CALLBACKS
    CCeditbox1_h.Tag    = 'CC.N';
    CCeditbox2_h.Tag    = 'CC.GROUPS';
    CCeditbox3_h.Tag	= 'CC.PROB_COPY';
    CCeditbox4_h.Tag	= 'CC.PROB_CONTRARIAN';
    CCpopupmenu5_h.Tag  = 'CC.TYPE';
    
    CCeditbox1_h.Callback   = @edit_fun;
    CCeditbox2_h.Callback   = @edit_fun;
    CCeditbox3_h.Callback   = @edit_fun;
    CCeditbox4_h.Callback   = @edit_fun;
    CCpopupmenu5_h.Callback = @edit_fun;
    
    

end